## Arrays

In [1]:
first_array = [5,3,2,1,4]

5-element Array{Int64,1}:
 5
 3
 2
 1
 4

In [2]:
print(first_array)

[5, 3, 2, 1, 4]

In [3]:
typeof(first_array)

Array{Int64,1}

In [4]:
ndims(first_array)

1

## Initialization of Arrays

In [6]:
a_zeros = zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [7]:
a_ones = ones(9)

9-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [8]:
fill(2,5)

5-element Array{Int64,1}:
 2
 2
 2
 2
 2

In [10]:
fill(2,(5,5))

5×5 Array{Int64,2}:
 2  2  2  2  2
 2  2  2  2  2
 2  2  2  2  2
 2  2  2  2  2
 2  2  2  2  2

## Combining Arrays

In [11]:
array_1 = [7,8,9]
array_2 = [1,2,4]

3-element Array{Int64,1}:
 1
 2
 4

In [12]:
array_v = vcat(array_1, array_2)

6-element Array{Int64,1}:
 7
 8
 9
 1
 2
 4

In [20]:
ndims(array_v)

1

In [21]:
typeof(array_v)

Array{Int64,1}

In [13]:
array_h = hcat(array_1,array_2)

3×2 Array{Int64,2}:
 7  1
 8  2
 9  4

In [19]:
ndims(array_h)

2

In [22]:
typeof(array_h)

Array{Int64,2}

## Two Dimentional Arrays

In [15]:
dataset = [[1,2],[5,6]]

2-element Array{Array{Int64,1},1}:
 [1, 2]
 [5, 6]

In [25]:
[1 2;5 6]

2×2 Array{Int64,2}:
 1  2
 5  6

## Indexing

In [33]:
a1 = [3,4,5,1,2,4,12,22]

8-element Array{Int64,1}:
  3
  4
  5
  1
  2
  4
 12
 22

In [35]:
a1[1]

3

In [36]:
a1[7]

12

In [37]:
a2 = [5 3 1;3 4 6]

2×3 Array{Int64,2}:
 5  3  1
 3  4  6

In [38]:
a2[2,3]

6

In [41]:
a2[2,:]

3-element Array{Int64,1}:
 3
 4
 6

In [43]:
a2[:,2]

2-element Array{Int64,1}:
 3
 4

## Slicing

In [44]:
data = [0.23 2 0.34 4 1; 0.33 3.4 0.24 3.2 2; 0.43 2.7 0.14 2.5 1]

3×5 Array{Float64,2}:
 0.23  2.0  0.34  4.0  1.0
 0.33  3.4  0.24  3.2  2.0
 0.43  2.7  0.14  2.5  1.0

In [57]:
data[:,1:end-1]

3×4 Array{Float64,2}:
 0.23  2.0  0.34  4.0
 0.33  3.4  0.24  3.2
 0.43  2.7  0.14  2.5

In [58]:
data[:,end]

3-element Array{Float64,1}:
 1.0
 2.0
 1.0

In [56]:
x,y=data[:,1:end-1],data[:,end]

([0.23 2.0 0.34 4.0; 0.33 3.4 0.24 3.2; 0.43 2.7 0.14 2.5], [1.0, 2.0, 1.0])

In [59]:
x

3×4 Array{Float64,2}:
 0.23  2.0  0.34  4.0
 0.33  3.4  0.24  3.2
 0.43  2.7  0.14  2.5

In [60]:
y

3-element Array{Float64,1}:
 1.0
 2.0
 1.0